### ISSUE TITLE
Prepare CSIS Acceptance Tests

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/csis-technical-validation#1]
We have to perform acceptance tests to ensure that our "minimal viable product" is "fit for purpose", that is, it delivers the proposed value.

Each partner must name two persons from its organization for the [CSIS Testing Team](https://github.com/orgs/clarity-h2020/teams/csis-testing-team) to perform the testing of the CSIS. We must prepare a bullet point of actions that the user has to test. We use this GitHub issue as a first step to collect the appointed tester names. We create a dedicated repository for testing. Then we create a separate issue for each organisation. If the tester encounters any problem a comment should be added to the respective issue.

**Tasks:**
- [x] define test specification 
- [x] collect tester names
- [x] create individual issues

**List of Testers:**

Organisation | Tester 1 | Tester 2
-- | -- | --
AIT | @aitdrazen | @Itsman-AT
ATOS | @DanielRodera   |  @negroscuro 
CIS | @p-a-s-c-a-l   |  @therter 
SMHI | @LenaStr  |  @yhundecha
METEOGRID | @ghilbrae | @emiliodediego
ZAMG | @claudiahahn |  @RobAndGo 
LUPT-PLINIVS |  @mattia-leone | @stefanon 
StockCity | @Stock1Christer |  @Magnus1281
EUREKA |  @Mauro-Iorio |  **n/a**
NAPOLI | @pignataro |  **n/a**
AEMET | @mpostigog   |  **n/a**
WSP | @WSPAnna  |  @gunillakaiser
ACCIONA | **n/a** | **n/a**
SCC | **n/a** | **n/a**
CABJOM | @manslindell  | @AnkiAlmer
CEDEX | @lparracedex | @MPerelli 
LINZ | @Linz-PTU  | **n/a**

**Comment by p-a-s-c-a-l** [comment]
> Trying to put my username in....hmmmm, can't edit. Working on it! Or is it You Pascal that put in our names above? For CABJON me and Anki will be the testers...

@manslindell You cannot edit until you're a member of the clarity-h2020 organisation. I've sent an invitation.

**Comment by manslindell** [comment]
Yepp, done!
ml

Måns Lindell
010-2236408

För information om hur Länsstyrelsen behandlar personuppgifter,
se www.lansstyrelsen.se/dataskydd<http://www.lansstyrelsen.se/dataskydd>

Från: Pascal Dihé <notifications@github.com>
Skickat: den 20 januari 2020 15:08
Till: clarity-h2020/csis-technical-validation <csis-technical-validation@noreply.github.com>
Kopia: Lindell Måns <Mans.Lindell@lansstyrelsen.se>; Mention <mention@noreply.github.com>
Ämne: Re: [clarity-h2020/csis-technical-validation] Prepare CSIS Acceptance Tests (#1)


Trying to put my username in....hmmmm, can't edit. Working on it! Or is it You Pascal that put in our names above? For CABJON me and Anki will be the testers...

@manslindell<https://github.com/manslindell> You cannot edit until you're a member of the clarity-h2020 organisation. I've sent an invitation.

**Comment by DanielRodera** [comment]
I will test for Atos.

**Comment by WSPAnna** [comment]
Pascal, from WSP it will be me and Gunilla Kaiser that enter the system (although she's out of office most of the week so not sure that she can solve it before Friday). However, as Måns was writing previously - I'm having the same problem, I really do not understand how to 1) add my name to the list above and 2) what/how to do next to really give any substantial input. Perhaps you could add some more instructions for us users that are not familiar to Github?

**Comment by p-a-s-c-a-l** [comment]
> I really do not understand how to 1) add my name to the list above and 2) what/how to do next to really give any substantial input. Perhaps you could add some more instructions for us users that are not familiar to Github?

@WSPAnna 

No worries. :-) I'll update the list above. At the moment, I just need the GitHub account names of the testers. When Gunilla and Anki have created their account, they just have to add a comment to this issue.  

Once we've collected all the names **and** public CSIS is available, I'll provide detailed instructions for testers.

**Comment by yhundecha** [comment]
Hi Pascal, I am one of the testers for SMHI together with Lena.
Yeshewa.

**Comment by AnkiAlmer** [comment]
Hi, Pascal. Have now managed to create an account and are ready to start testing for CABJON. :-)

**Comment by pignataro** [comment]
hi, 
I will be tester for NAPOLI. we are deciding on the second name.

**Comment by ghilbrae** [comment]
Hi! I've added myself as tester for Meteogrid. The other person will be @emiliodediego who has already created a github account but needs to be added to clarity.

**Comment by gunillakaiser** [comment]
I am registred as WSP user

**Comment by Mauro-Iorio** [comment]
Hi Pascal I need to become member of the clarity-h2020 organisation to be a Tester of Eureka

**Comment by Stock1Christer** [comment]
I am registered as one of the StockCity partner.

**Comment by Linz-PTU** [comment]
Hi Pascal,

the testers of the City of Linz will be:

- Wilfried Hager (wilfried.hager@mag.linz.at)
- Anna Sonnleitner (anna.sonnleitner@mag.linz.at)

Kind regards
Wilfried

**Comment by DenoBeno** [comment]
I will be testing on top of the "official" AIT testers. Still not sure who the official ones will be - Tanja says that they have some students who will do the initial testing and I want to have some more senior and not so technical people (e.g. Gerald, Patrick Zwickl, Tanja) involved for later testing.

**Comment by MPerelli** [comment]
Hi Pascal,

the testers from CEDEX willl be:

Laura Parra (username: lparracedex & email: laura.parra@cedex.es)
Marcos Perelli (username: MPerelli & email: marcos.perelli@cedex.es)

Regards,
Marcos

**Comment by patrickkaleta** [comment]
For AIT the testers will be:
- Drazen: @aitdrazen 
- Jan: @Itsman-AT

**Comment by mpostigog** [comment]
I will test for AEMET

**Comment by p-a-s-c-a-l** [comment]
FYI: The [Acceptance Test Specification](https://github.com/clarity-h2020/csis-technical-validation/wiki/Acceptance-Test-Specification) is available now. 
[CSIS Public BETA Release](https://github.com/clarity-h2020/csis/issues/145) is still in preparation, we will being with the tests once the public system is operational.

**Comment by p-a-s-c-a-l** [comment]
We are now creating separate issues for acceptance tests.

**Comment by p-a-s-c-a-l** [comment]
done
